feat: support ecotone
kroma-network/zkevm-circuits pull request #39
Opened 2024-04-23 01:59 UTC by chokobole

# Description

This PR updates fee collection logic for Optimism Ecotone.

See https://specs.optimism.io/protocol/exec-engine.html#ecotone-l1-cost-fee-changes-eip-4844-da

2024-04-23 04:02 UTC, dongchangYoo requested changes

2024-04-23 04:02 UTC, dongchangYoo commented on bus-mapping/src/state_db.rs
> +        use eth_types::ToBigEndian;
did you intend to insert this line here?

2024-04-23 04:02 UTC, dongchangYoo commented on bus-mapping/src/state_db.rs
> +        ]);
```suggestion
        let l1_base_fee_scalar = u32::from_be_bytes(
            l1_base_fee_scalar_bytes[L1_BASE_FEE_SCALAR_OFFSET..(L1_BASE_FEE_SCALAR_OFFSET + 4)]
                .try_into()
                .expect("slice with incorrect length"),
        );
```

2024-04-23 04:02 UTC, dongchangYoo commented on bus-mapping/src/state_db.rs
> +        ]);
```suggestion
        let l1_blob_base_fee_scalar = u32::from_be_bytes(
            l1_base_fee_scalar_bytes
                [L1_BLOB_BASE_FEE_SCALAR_OFFSET..(L1_BLOB_BASE_FEE_SCALAR_OFFSET + 4)]
                .try_into()
                .expect("slice with incorrect length"),
        );
```

2024-04-23 04:03 UTC, dongchangYoo commented
please change minor version of the zkevm-circcuit, see `zkevm-circuits/src/version.rs`

2024-04-23 04:19 UTC, TomTaehoonKim requested changes

2024-04-23 04:19 UTC, TomTaehoonKim commented on mock/src/test_ctx.rs
>          // validator reward scalar: 2000
```suggestion
        // validator reward scalar: 5000
```

2024-04-24 05:58 UTC, chokobole commented on bus-mapping/src/state_db.rs
> +        use eth_types::ToBigEndian;
This is needed , without it, we have this error.

```rust
error[E0599]: no method named `to_be_bytes` found for struct `eth_types::U256` in the current scope
   --> bus-mapping/src/state_db.rs:342:59
    |
342 |         let l1_base_fee_scalar_bytes = l1_base_fee_scalar.to_be_bytes();
    |                                                           ^^^^^^^^^^^ method not found in `eth_types::U256`
```

2024-04-24 06:11 UTC, dongchangYoo approved these changes
LGTM

2024-04-24 10:54 UTC, TomTaehoonKim approved these changes
LGTM

2024-04-24 11:55 UTC, merged